//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zibay
{
    using System;
    using System.Collections.Generic;
    
    public partial class frosh
    {
        public int ID { get; set; }
        public Nullable<int> id_costumer { get; set; }
        public Nullable<int> id_kala { get; set; }
        public string date_frokhte { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual kala kala { get; set; }
    }
}
